### ISSUE TITLE
fix: create config page

### ISSUE THREAD

**Issue by yudai09** [yudai09/redmine_phonecall#3]
設定を実施できるページを作ってください。

**Comment by volreijy** [comment]
設定ページを追加
画面への行き方：管理 -> プラグイン -> 設定
Twilioの設定とエスカレーションの設定はDBにもたせていたが、
複数必要なわけではないため、Redmine標準の簡易設定(Hash)で持たせるようにしました。

**Comment by volreijy** [comment]
fix_create_config_page
